### PR TITLE
(Extremely) minor changes in readme text

### PR DESCRIPTION
**Pull request by mehmandarov**

### CODE REVIEW

**Comment by OndrejM** [comment]
Hi @mehmandarov , thank you for these suggestions. This PR didn't pass Eclipse validations. Have you signed the Eclipse Contributor Agreement already - https://www.eclipse.org/legal/ECA.php?

Since the changes are very minor, if you don't want to bother with the ECA I can do the changes myself. But signing the ECA would help if you contribute to any Eclipse project in the future anyway, so I encourage you to do that :-)

**Comment by mehmandarov** [comment]
Yes, I have done that. Not sure though how to check if it is ok now?

**Comment by mehmandarov** [comment]
@Emily-Jiang: I am trying to do that. I have managed to signe off the last commit and have signed up for ECA, but it still seems to fail. Any proper way of checking that without pushing a new commit?

**Comment by Emily-Jiang** [comment]
The other suggestion is to squash the commits or ditch this one and create a new one PR.

**Comment by mehmandarov** [comment]
Ok, I will send another request. Closing this one. Sorry about that. Just want to get this IP-validation thing sorted.

**Pull request closed without merging**
