### PR TITLE
Use Microprofile BOM/POM #35

### PR DESCRIPTION
**Pull request by keilw**
Successfully switched `java-ee-api` 7.0 to `microprofile` 1.0.0. Everything builds as it did before. 
For consistency I changed the groupId to `io.microprofile` for 1.0.0, the packages are as they were but we cannot rewrite history so it should be fine.

Task-Url: https://github.com/eclipse/microprofile-samples/issues/35

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I thought we'd decided that samples and conf demo weren't going to be released with a 1.0 tag as it was deemed too complicated as they're already part of Eclipse

**Comment by struberg** [comment]
That was also my understanding from the discussions during the Microprofile hangout. 
Plus who does really need it? Let's rather focus on 1.1

**Comment by keilw** [comment]
Do we want to stick with just a release tag and the BOM in one or the other repo?
This is proof, the BOM works. If we don't want to make it available, never mind but except for the groupId the dependency change is like it must be in the future. Whether using this PR or rewriting it, not a big difference. It works using the BOM. If PR rather hides the BOM, well it is out now, so that part of the hangout is done and if it is not meant to be used so widely, I am pretty sure having it in JCenter only makes little difference.

**Comment by keilw** [comment]
So the 3rd commit puts the version number to a 1.1 Snapshot. As long as no stable 1.1 BOM exists somewhere, this is a working sample (until Java EE 8 API is Final it also had to use EE 7 ;-) so unless somebody wants to completely eliminate these samples by Antonio it works now, CI passes, so we skip tagging them until a 1.1 release may some time be possible (it certainly won't be delayed by those samples as you know)

**Comment by keilw** [comment]
@kwsutter @jclingan I leave it to you what to do about samples. 
The way I use them is at DemoCamps, Conferences, etc. showing people how something works, but also allowing them to use and try it themselves. This has been quite succesful at Eclipse DemoCamps or similar events. Might speak to @ivargrimstad @gunnarmorling @atsticks or others next week during JavaLand how they would like to use them, or if they have their own. Either way the demos should work and at least pass in some CI server (Jenkins in future if we get it running? ;-) even if they may not officially be offered to download. If MP 1.0 BOM exists IMO they should have been tagged accordingly, but I don't really mind if we did it under "org.eclipse" as the last state of the PR. It would only require a 1.0 version number but if we don't tag it till 1.1.x I'd be fine too, but then please tag things that match together.

**Comment by kwsutter** [comment]
Werner, now that we're making progress on the MicroProfile 1.1 BOM (in the eclipse/microprofile-bom repo), how about if we update this PR to reference the 1.1.0-SNAPSHOT and get that working?  That would be a good validation of the new bom contents and it would make these Samples more usable.  Thanks.

**Comment by keilw** [comment]
Will check it out today or tomorrow (it is a long holiday, so a bit of time;-)

**Comment by keilw** [comment]
Almost there. Ideally I also plan to use some of them for the DWX '17 talk I got with @ivargrimstad next week: http://www.developer-week.de/Programm/Veranstaltung/(event)/21467

**Comment by keilw** [comment]
The problem is, at least the README file was changed in https://github.com/eclipse/microprofile-samples/pull/40, so I would rather close this and open a new PR after https://github.com/eclipse/microprofile-samples/pull/40 was merged.   @kwsutter when do you think it could be merged?

**Pull request closed without merging**
